### ISSUE TITLE
How to prepare _cut.csv files?

### ISSUE THREAD

**Issue by pressureless** [squidrice21/StripMaker#2]
README says `New SCAP files can be generated from SVG files using the python/visualization/svg_to_scap_width_exact.py.`

It seems `run_prediction.py` also needs `_cut.csv/_uncut.csv`.

<img width="830" alt="image" src="https://github.com/squidrice21/StripMaker/assets/8511053/d9ee8f58-36b5-4f11-b501-cd65b00b66c9">
<img width="889" alt="image" src="https://github.com/squidrice21/StripMaker/assets/8511053/094831ee-3e0b-4e11-93f1-f90edb709625">

**Comment by pressureless** [comment]
If those two lines were commented, then the program could generate some results. Not sure whether it would make a difference with `_cut/_uncut csv` files.

**Comment by squidrice21** [comment]
The problem was caused by a parsing error when there was no cut file. I have updated the script to fix this issue.

The `_cut.csv` file is related to preprocessing. This preprocessing is used to cut "zig-zag" overdrawing (one can overdraw without pen-up) and remove small hooks which are common at the ends of human-drawn strokes. The reason that this information is included is that the preprocessing is not 100% correct (especially when the input stroke has high-curvature locations) and sometimes can cause StrokeStrip parameterization failures (when the strip is complicated like the cursive letter examples in the paper), and with this information, the code can retry after connecting some cut points.

I didn't include the exact preprocessing process in this repo since my actual setup involved some old code that is hard to include here. If you want to cut "zig-zag" strokes and remove the hooks from your own inputs, you can take a look at [this entrance](https://github.com/squidrice21/StripMaker/blob/main/src/MainPreprocess.cpp). This is the preprocessing used in StrokeStrip which works for most cases.

**Comment by pressureless** [comment]
Got it, thank you!
